### PR TITLE
Implements TestHandler and unit tests, fix #5

### LINKED ISSUE #5: Testing feature
Property (core CI feature 2 - testing): 
The CI server supports executing the automated tests of the group project. 

**Requirements**
 * Testing is triggered as webhook, on the branch where the change has been made, as specified in the HTTP payload.

### PR DESCRIPTION
**Pull request by darkway-s**
Fixes #5 
Implements TestHandler, extends from CompileHandler
Implements 2 unit tests, including positive and negative circumstances.

### CODE REVIEW

**Comment by darkway-s** [comment]
It also contains  some refractors in CompileHandler to make it suitable for inheritance.
Mainly the visibility of the methods and members.

**Comment by darkway-s** [comment]
> For the test that tests if test fails I think it would be better to create a new branch (test/test-fail) that contains a test that will not pass. Because now it is failing due to a build fail and not a test failure.

Yes, I just get one fail test directly from the a commit in main branch. I'll then separate it the test/test-fail branch.

**Review by amandakrohn — APPROVED** [review]
Nice! LGTM!

**Comment by darkway-s** [comment]
If there is more need to run commands on the commit repo, I think we can make a template class CommandHandler for running commands. And every time you want to run command "Abc De", the only thing to do is initialize the CommandHandler with the parameter String["Abc", "De"].

**Pull request merged**
