### PR TITLE
Implementation of Build class which stores info about a build, feat #15

### LINKED ISSUE #15: Build class to store info about a specific build
The purpose of this class is to store relevant information when a new build is triggered. This object can be sent as a parameter to the Notification handler when everything is ready.

Fields which I believe is relevant now includes: 
- PR-id
- Email
- Build status
- Test status

### PR DESCRIPTION
**Pull request by ludwigjo**
This PR introduces a new class which is intended to store the info about the current build.

The test cases can be extended further later on with data from an actual build and clone. 

Closes #15

### CODE REVIEW

**Review by amandakrohn — COMMENTED** [review]
Nice!

I think it would be good to add a constructor which takes all the parameters? In case we want to add all the parameters at once (nicer to have a constructor for that instead of having to add every parameter with a setter).

**Comment by ludwigjo** [comment]
@amandakrohn Yeah, good point! I'll add that.

**Review by Sefik-Palazoglu — APPROVED** [review]
LGTM! Please open another issue about extending the test cases after merging this.

**Review by amandakrohn — APPROVED** [review]
LGTM!

**Pull request merged**
